%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Medium Length Professional CV
% LaTeX Template
% Version 2.0 (8/5/13)
%
% This template has been downloaded from:
% http://www.LaTeXTemplates.com
%
% Original author:
% Rishi Shah 
% Modified by:
% Aritz Lizoain
%
% Important note:
% This template requires the resume.cls file to be in the same directory as the
% .tex file. The resume.cls file provides the resume style used for structuring the
% document.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%----------------------------------------------------------------------------------------
%	PACKAGES AND OTHER DOCUMENT CONFIGURATIONS
%----------------------------------------------------------------------------------------

\documentclass{resume} % Use the custom resume.cls style
\usepackage{mathptmx} % Times New Roman font
\def\Plus{\texttt{+}}
\usepackage{multicol} %multicols nik jarrita
\hyphenpenalty=10000
\usepackage[left=0.6in,top=0.7in,right=0.65in,bottom=0.7in]{geometry} % Document margins
\newcommand{\tab}[1]{\hspace{.2667\textwidth}\rlap{#1}}
\newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}

%links
\usepackage{xcolor}
\usepackage[colorlinks = true,
            linkcolor = blue,
            urlcolor  = blue,
            citecolor = blue,
            anchorcolor = blue]{hyperref}

\newcommand{\MYhref}[3][blue]{\href{#2}{\color{#1}{#3}}}%

    \usepackage[absolute]{textpos}
    \setlength{\TPHorizModule}{30mm}
    \setlength{\TPVertModule}{\TPHorizModule}
    \textblockorigin{-6mm}{32mm} % start everything near the top-left corner
    \setlength{\parindent}{0pt}
    
\usepackage{graphicx}

\usepackage{tikzpagenodes}

\usepackage{fontawesome}


% \name{Aritz Lizoain} % Your name
% %\address{156 Kasturi, Balajinagar, Sangli 416416} % Your address
% %\address{123 Pleasant Lane \\ City, State 12345} % Your secondary addess (optional)
% \address{{(\Plus 41) 77 991 82 14 $|$ lizoain.ac@gmail.com  $|$ 19.12.1998 Spain}}% Your phone number and email

\begin{document}

\vspace{-0.85in}
\textbf{Aritz Lizoain} \newline
Date of Birth: 19.12.1998 \newline
Nationality: Spanish \newline
E-mail: lizoain.ac@gmail.com \newline
Phone number: (\Plus 41) 77 991 82 14
\vspace{-25pt}

\begin{tikzpicture}[remember picture,overlay,shift={(current page.north east)}]
\node[anchor=north east,xshift=-0.65in,yshift=-0.5cm]{\includegraphics[width=3cm]{photo_reduced.jpg}};
\end{tikzpicture}

\vspace{20pt}
%----------------------------------------------------------------------------------------
%	EDUCATION SECTION
%----------------------------------------------------------------------------------------
\begin{rSection}{{\large Education}}
\begin{itemize}
    

 \item {\bf University of Cantabria} \hfill {\bf Santander, Spain} \newline {Bachelor of Science in Physics }\hfill{\em August 2016 - September 2020}  
\newline
{\bf Relevant courses: }%Advanced Computation, Programming, Numerical Methods, Laboratory Computational Tools, Advanced Experimental Techniques (with honors), Ordinary Differential Equations, Partial Differential Equations, Differential Calculus, Integral Calculus, Linear Algebra and Geometry %4 lines
%Advanced Computation, Programming, Numerical Methods, Laboratory Computational Tools, Advanced Experimental Techniques (with honors), Ordinary Differential Equations, Partial Differential Equations, Differential Calculus, Integral Calculus, Linear Algebra %3 lines full
Advanced Computation, Programming, Numerical Methods, Laboratory Computational Tools, Advanced Experimental Techniques (with honors), Ordinary and Partial Differential Equations, Linear Algebra, Differential and Integral Calculus. %3 lines
%Advanced Computation, Programming, Numerical Methods, Laboratory Computational Tools, Advanced Experimental Techniques (with honors), ODE, PDE, Differential and Integral Calculus, Linear Algebra %2.5 lines

\newline
{\bf Relevant topics: }Data processing, numerical analysis, object-oriented programming, probability and statistics, software development.


\item {\bf University of Zurich / Erasmus\Plus} \hfill {\bf Z{\"u}rich, Switzerland} \newline {Bachelor of Science in Physics }\hfill{\em August 2018 - September 2019}  
\newline
{\bf Relevant courses: }Statistical Mechanics and Molecular Simulations.
\newline

\end{itemize}
\end{rSection}
\vspace{-12pt}

%--------------------------------------------------------------------------------
%    Projects And Seminars
%-----------------------------------------------------------------------------------------------
\begin{rSection}{\large{Experience \& Projects {\href{https://github.com/aritzLizoain}{\faicon{github}}}}}

\begin{itemize}
%\item
\subsection*{\href{https://github.com/aritzLizoain/CNN-Image-segmentation}{CNN Image segmentation}}
\vspace{-8pt}
{\em Duration: 7 months}
%{\em February 2020 - Present}
\begin{itemize}
\item %so it shows all the other ones

 \item Developed a deep learning application for research on dark matter. The software performed multi-class image segmentation on images from direct detection experiments. Worked in the implementation of:

 \begin{itemize}
     \item Image pre-processing
     \item Network structure and parameter optimization
     \item Model training and testing
 \end{itemize}

  %OpenCV-Python

 \item Employed main packages: TensorFlow, Keras, scikit-learn, OpenCV, scikit-image, Pandas, NumPy.
 
  \item As a result of the obtained exceptional results, offered the opportunity to contribute in the 'DarkMachines' collaboration.

\end{itemize}

\vspace{-8pt}
\subsection*{MD simulation}
\vspace{-8pt}
{\em Duration: 5 months}
%{\em September 2019 - January 2020}
\begin{itemize}
\item %so it shows all the other ones
\item Designed and developed a molecular dynamics software in Java, with the assistance of a Fortran90 code, obtaining an outstanding grade in the Advanced Computation course.
\item Excellent group communication and organization established. The team was highly focused on specific customer needs; experience, modularity and performance.
    \item Programming knowledge: software modeling (UML), computational complexity and algorithmic efficiency.

\end{itemize}
%\end{multicols}
    
% FOR MOTIVATION LETTER Data analysis knowledge applied in a wide range of fields, such as astrophysics, particle physics, optics, physical chemistry or materials science.
%Knowledge including database information selection and extraction, numerical calculations, data selection, Jupyter Python usage, finding best fitting processes with Matlab, representation with Mathematica, visualization, numerical methods , 

\end{itemize}
\end{rSection}


%\vspace{-4.15pt}

%----------------------------------------------------------------------------------------
%	TECHNICAL STRENGTHS SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{\large{Skills \& Interests}}
\vspace{-9.15pt}
\begin{multicols}{3}

\begin{itemize}
    

\item
{\bf Technical Skills: }
\vspace{-5pt}
\begin{itemize}\setlength\itemsep{-8.5pt}
    \item Python
    \item Java
    \item MATLAB
    \item SQL
    \item Wolfram Mathematica
    
\end{itemize}
\item
{\bf Languages:}
\vspace{-5pt}
\begin{itemize}\setlength\itemsep{-6.5pt}
    \item Spanish (native)
    \item Basque (native)
    \item English (advanced C1)
    \item French (intermediate B1)
\end{itemize}

\item
{\bf Achievements and Interests:}
\begin{itemize}\setlength\itemsep{-8.5pt}
    \item Earned the International Diploma in Physics
    \item Studying machine learning applications
    \end{itemize}

\end{itemize}
\end{multicols}
\end{rSection}

%NO SPACE BELOW!!!!!!!!
%NO SOFT SKILLS AND UNRELATED HOBBIES OR SKILLS (BS ADVICE)
\end{document}
